### ISSUE TITLE
Erro ao iniciar o devContainer

### ISSUE THREAD

**Issue by rfl-designer** [prontostack/pronto-fuel#1]
Olá estou recebendo um erro que não consigo resolver.

![image](https://user-images.githubusercontent.com/74984433/162765962-2e7ceb57-0cf2-478c-8910-2e24acd292d6.png)

Por gentileza você consegue me ajudar. Achei muito bacana o seu setup, passei a te acompanhar no Youtube.

**Comment by rfl-designer** [comment]
Consegui adicionar o sail e funcionou, desculpa incomodar, mas parabéns pelo setup!

**Comment by MtDalPizzol** [comment]
Opa... Qual foi a solução, @rfl-designer ?

**Comment by rfl-designer** [comment]
> Opa... Qual foi a solução, @rfl-designer ?

Eu adicionei o Laravel Sail ao invés de usar o Dev Container. Como já tenho uma certa experiência com o Sail foi mais fácil usar a stack.
