### ISSUE TITLE
Nome do DB_HOST no arquivo .env

### ISSUE THREAD

**Issue by EduVillas** [prontostack/pronto-fuel#12]
Eu não conseguia conectar com o mariadb/mysql e conclui que precisa alterar no arquivo `.env` o nome do host

`DB_HOST=mariadb`
para
`DB_HOST=mariadb-1`
Onde mariadb-1 seria o nome do container no docker

**Comment by MtDalPizzol** [comment]
Oi, Edu. A princípio o nome do `DB_HOST` deveria ser o mesmo nome do serviço no `docker-compose.yml`, e não o nome do container. Não sei o que pode ter ocorrido no seu caso.
