### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by jcgava** [prontostack/pronto-fuel#3]
Boa tarde, estou tentando colocar em produção um projeto, porém quando rodo build e subo para servidor não encontra o arquivo app.js, alterei todas as variáveis no .env.
Poderia dar uma ajuda.

**Comment by MtDalPizzol** [comment]
Olá, amigo. O branch `main` do repositório atual está com problema na configuração para build, de fato. Ainda não tive tempo de enviar uma correção. Eu cheguei a corrigir o problema mas em outro branch chamado `cypress`. Você pode conferir as modificações que fiz no commit daquele branch aqui: https://github.com/prontostack/pronto-fuel/commit/38a8e7cf174627a4782992c66e274aa92fbf1e3e

São basicamente configurações de locais de arquivos e esse tipo de coisa. Creio que o grosso das alterações relevantes pra você tenha sido no arquivo `vite.config.js`.

Agora que o o Laravel passou para o Vite por padrão, eu irei revisar esse repo para adotar as atualizações, já que eu desenvolvi o Fuel como uma alternativa Vite para o Laravel que na época só suportava o Mix com o Webpack. Mas isso provavelmente só irá ocorrer mês que vem. Creio que investigando o commit do link você será capaz de resolver o seu problema.

**Comment by nathanraposo** [comment]
Seria interessante, fazer um vídeo para seu canal Configurando Laravel com docker + vite!

**Comment by MtDalPizzol** [comment]
Fala, turma! Acabei de enviar um novo release que deve resolver os problemas descritos aqui.

https://github.com/prontostack/pronto-fuel/releases/tag/0.0.1
