### ISSUE TITLE
Adicionar o link do video youtube

### ISSUE THREAD

**Issue by wesllycode** [prontostack/pronto-fuel#6]
**Sugestão**

Adicionar no readme.md o link do vídeo para ajudar as pessoas quem quer seguir por vídeo como usar esse repositório.
https://www.youtube.com/watch?v=IzQxyZD2EXQ

**Comment by MtDalPizzol** [comment]
@wesllycode Valeu pela sugestão. Eu pretendo gravar um novo vídeo mostrando as atualizações que foram enviadas essa semana. Aí coloco esse vídeo atualizado no README.
