### ISSUE TITLE
Ray não funciona no Arch Linux

### ISSUE THREAD

**Issue by fhilipecrash** [prontostack/pronto-fuel#7]
Boa tarde, eu rodei o projeto e ao tentar debuggar com o Ray perceni que ele não captura os erros do Laravel por conta do Docker, tentei resolver o problema pesquisando na documentação do Ray mas não resolveu. Talvez seja alguma configuração que eu esqueci ou então só não funciona mesmo

**Comment by MtDalPizzol** [comment]
@fhilipecrash Difícil ajudar em casos assim. Pode ser algum mapeamento de porta que não esteja correto do Docker para o host, ou a forma de rodar o Ray, ou uma série de outros fatores que não sejam diretamente relacionados ao repositório. Caso você identifique algo que torne mais evidente ser um problema com o repositório, vamos dar sequência. Vou manter o issue aberto por enquanto.

**Comment by fhilipecrash** [comment]
@MtDalPizzol eu mesmo acredito que seja mais um problema do Docker, em relação ao mapeamento das portas. mais tarde eu vou tentar outras formas de fazer funcionar e caso consiga eu coloco a resolução nessa issue pois poderá servir de ajuda pra outras pessoas com o mesmo problema

**Comment by fhilipecrash** [comment]
acabei descobrindo [nessa issue](https://github.com/spatie/ray/issues/705) que eu só não tinha liberado o acesso a porta no meu firewall 😅
bom posso dar como encerrada essa issue
