### ISSUE TITLE
Responsividade do menu lateral

### ISSUE THREAD

**Issue by wesleycavalcante** [prontostack/pronto-fuel#8]
Quando a resolução está entre de 1024w e 600w o menu lateral fica com bug, ele fica meio que na versão mobile (abaixo de 600w), sempre visível e não fecha com o movimento touch.

<img width="844" alt="Captura de Tela 2022-08-25 às 07 23 40" src="https://user-images.githubusercontent.com/30080815/186651748-16682541-5663-483e-a8ba-c2ca80d96a03.png">

**Comment by wesleycavalcante** [comment]
Cara, que resposta rápida, coloquei aqui 599 (o 600 exato ainda ficava com problema) e parece ter resolvido, desde já muito obrigado e parabéns pelo starter kit, pretendo usá-lo nos meus futuros projetos.

**Comment by MtDalPizzol** [comment]
A princípio esse commit deve ter resolvido os problemas relativos à responsividade da NavDrawer: https://github.com/prontostack/pronto-fuel/commit/8ab1b390d22d032b94c419e9e73c690116152af9
